### ISSUE TITLE
Guia Objetos 2 - Ejercicio 3

### ISSUE THREAD

**Issue by GOrellanoGL** [GonzaRom/Guia_Lab3_Objetos2#1]
Gonza: te dejo por aca lo que vi que me pasaste.

En la cuenta del titular lo que seria el uuid, sacaria el setID y pondria esto -> this.uuid = UUID.randomUUID();  (Acordate que en los contructores vos pasas parametros y asignas a variables, no haces ningun llamado de metodos)

Lo mismo que te puse mas arriba pasa en la clase de la cuenta corriente. Si vas a usar una constante que sea privada porque la vas a utilizar en esa misma clase y no queremos que esto se vea en otras clases (encapsulamiento). En cuanto a los contadores esta mal que los setees en el constructor, los podes inicializar directamente con un valor por defecto, en cero por ejemplo y listo.

**Comment by GonzaRom** [comment]
Entonces el setID se va y lo que estaba dentro de ese método lo igualó a la variable uuid (usando this.) ¿ dentro del constructor o cuando los inicializo ?

**Comment by GOrellanoGL** [comment]
claro haces esto en el constructor -> this.uuid = UUID.randomUUID();

**Comment by GonzaRom** [comment]
Excelente. Gracias por el feedback!
